---
  - name: update packages
    become: yes
    apt:
      upgrade: yes
  - name: install nodejs, npm and pm2
    become: yes
    apt:
      name: [nodejs, npm]
      state: latest
      update_cache: yes
  - name: install pm2
    become: yes
    shell: npm install pm2 -g
